services:
  web:
    build:
      context: .
      target: build        # مرحلة البناء (فيها أدوات التطوير)
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - .:/app             # مزامنة الكود للتحديث الحي
      - /app/node_modules  # حماية مكتبات الحاوية
    env_file:
      - .env.development